version: '3.3'
networks:
  proxy:
    external: true
services:
  api:
    build: 
      context: ..
      dockerfile: docker/api.dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - nginx
    restart: always
    networks: 
      - proxy
  web:
    build: 
      context: ..
      dockerfile: docker/web.dockerfile
    depends_on:
      - nginx
    ports:
      - "9002:3000"
    restart: always
    networks:
      - proxy
  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx.dockerfile
    ports:
     - "80:80"
    restart: always
    networks:
      - proxy




     
  
 
#docker-compose -p docker up --build
